//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAseguradorasB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_SegurosFalabellaEntities : DbContext
    {
        public bd_SegurosFalabellaEntities()
            : base("name=bd_SegurosFalabellaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Aseguradoras> tbl_Aseguradoras { get; set; }
        public virtual DbSet<tbl_Clientes> tbl_Clientes { get; set; }
        public virtual DbSet<tbl_Productos> tbl_Productos { get; set; }
        public virtual DbSet<tbl_Ventas> tbl_Ventas { get; set; }
    }
}
