//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAseguradorasB.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Productos()
        {
            this.tbl_Ventas = new HashSet<tbl_Ventas>();
        }
    
        public int prod_IdProductoPk { get; set; }
        [Display(Name = "Descripcion")]
        [Required(ErrorMessage = "{0} es requerido")]
        public string prod_Descripcion { get; set; }
        [Display(Name = "Prima")]
        public string prod_Prima { get; set; }
        [Display(Name = "Cobertura")]
        public string prod_Cobertura { get; set; }
        [Display(Name = "Asistencia")]
        public string prod_Asistencia { get; set; }
        [Display(Name = "Monto Venta")]
        public Nullable<int> prod_MontoVenta { get; set; }
        //[Display(Name = "Aseguradora")]
        public int prod_IdAseguradora_Fk { get; set; }
        public virtual tbl_Aseguradoras tbl_Aseguradoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ventas> tbl_Ventas { get; set; }
    }
}
